<?php

return [
    'configurable_approval' => [
        'label' => 'Konfigurasi Approval',
        'description' => 'Memilih approver berdasarkan user atau role untuk setiap alur approval.',
        'default' => true,
    ],
    'configurable_akta_workflow' => [
        'label' => 'Workflow Job Akta',
        'description' => 'Mengatur stage, penugasan, dan approval workflow Job Akta.',
        'default' => true,
    ],
    'menu_dashboard' => ['label' => 'Dashboard', 'description' => 'Menu Dashboard.', 'default' => true, 'menu' => true, 'paths' => ['dashboard']],
    'menu_master_wilayah_provinsi' => ['label' => 'Master Data - Provinsi', 'description' => 'Data provinsi.', 'default' => true, 'menu' => true, 'paths' => ['master-data/lokasi/provinsi']],
    'menu_master_wilayah_kota' => ['label' => 'Master Data - Kota', 'description' => 'Data kota.', 'default' => true, 'menu' => true, 'paths' => ['master-data/lokasi/kota']],
    'menu_master_wilayah_kecamatan' => ['label' => 'Master Data - Kecamatan', 'description' => 'Data kecamatan.', 'default' => true, 'menu' => true, 'paths' => ['master-data/lokasi/kecamatan']],
    'menu_master_wilayah_desa' => ['label' => 'Master Data - Desa', 'description' => 'Data desa/kelurahan.', 'default' => true, 'menu' => true, 'paths' => ['master-data/lokasi/desa']],
    'menu_master_bank' => ['label' => 'Master Data - Bank', 'description' => 'Data bank.', 'default' => true, 'menu' => true, 'paths' => ['master-data/bank']],
    'menu_master_developer' => ['label' => 'Master Data - Developer', 'description' => 'Data developer.', 'default' => true, 'menu' => true, 'paths' => ['master-data/developer']],
    'menu_master_broker' => ['label' => 'Master Data - Broker', 'description' => 'Data broker.', 'default' => true, 'menu' => true, 'paths' => ['master-data/broker']],
    'menu_master_notaris_rekanan' => ['label' => 'Master Data - Notaris Rekanan', 'description' => 'Data notaris rekanan.', 'default' => true, 'menu' => true, 'paths' => ['master-data/notaris-rekanan']],
    'menu_master_pekerjaan' => ['label' => 'Master Data - Pekerjaan', 'description' => 'Data pekerjaan.', 'default' => true, 'menu' => true, 'paths' => ['master-data/pekerjaan']],
    'menu_master_paket_pekerjaan' => ['label' => 'Master Data - Paket Pekerjaan', 'description' => 'Data paket pekerjaan/form order.', 'default' => true, 'menu' => true, 'paths' => ['master-data/form-order']],
    'menu_job_divisi' => ['label' => 'Job - Divisi', 'description' => 'Menu pekerjaan divisi.', 'default' => true, 'menu' => true, 'paths' => ['job/divisi', 'job/export-data?type=divisi']],
    'menu_job_operasional' => ['label' => 'Job - Operasional', 'description' => 'Menu pekerjaan operasional.', 'default' => true, 'menu' => true, 'paths' => ['job/ops', 'job/export-data?type=operasional']],
    'menu_job_notaris' => ['label' => 'Job - Notaris', 'description' => 'Menu pekerjaan notaris.', 'default' => true, 'menu' => true, 'paths' => ['job/akta/data', 'job/akta/filter-data/notaris', 'job/export-data?type=notaris']],
    'menu_job_ppat' => ['label' => 'Job - PPAT', 'description' => 'Menu pekerjaan PPAT.', 'default' => true, 'menu' => true, 'paths' => ['job/akta/filter-data/ppat', 'job/export-data?type=ppat']],
    'menu_job_waarmerking' => ['label' => 'Job - Waarmerking', 'description' => 'Menu pekerjaan waarmerking.', 'default' => true, 'menu' => true, 'paths' => ['job/akta/filter-data/waarmerking', 'job/export-data?type=waarmerking']],
    'menu_job_covernot' => ['label' => 'Job - Cover Note', 'description' => 'Menu pekerjaan cover note.', 'default' => true, 'menu' => true, 'paths' => ['job/akta/filter-data/covernot', 'job/export-data?type=covernot']],
    'menu_job_surat_keluar' => ['label' => 'Job - Surat Keluar', 'description' => 'Menu pekerjaan surat keluar.', 'default' => true, 'menu' => true, 'paths' => ['job/akta/filter-data/surat-keluar', 'job/export-data?type=surat-keluar']],
    'menu_job_legalisasi' => ['label' => 'Job - Legalisasi', 'description' => 'Menu pekerjaan legalisasi.', 'default' => true, 'menu' => true, 'paths' => ['job/akta/filter-data/legalisasi', 'job/export-data?type=legalisasi']],
    'menu_job_wasiat' => ['label' => 'Job - Wasiat', 'description' => 'Menu pekerjaan wasiat.', 'default' => true, 'menu' => true, 'paths' => ['job/akta/filter-data/wasiat', 'job/export-data?type=wasiat']],
    'menu_job_pajak' => ['label' => 'Job - Pajak', 'description' => 'Menu pekerjaan pajak.', 'default' => true, 'menu' => true, 'paths' => ['job/pajak', 'job/export-data?type=pajak']],
    'menu_job_pnbp' => ['label' => 'Job - PNBP/Voucher', 'description' => 'Menu PNBP/Voucher.', 'default' => true, 'menu' => true, 'paths' => ['job/pnbp', 'job/export-data?type=pnbp']],
    'menu_job_penambahan_item' => ['label' => 'Job - Penambahan Item', 'description' => 'Menu penambahan item.', 'default' => true, 'menu' => true, 'paths' => ['job/penambahan-item', 'job/export-data?type=penambahan-item']],
    'menu_job_pembatalan_item' => ['label' => 'Job - Pembatalan Item', 'description' => 'Menu pembatalan item.', 'default' => true, 'menu' => true, 'paths' => ['job/pembatalan-item', 'job/export-data?type=pembatalan-item']],
    'menu_bermasalah_freeze' => ['label' => 'Berkas Bermasalah - Freeze Job', 'description' => 'Daftar dan aksi freeze job.', 'default' => true, 'menu' => true, 'paths' => ['berkas-bermasalah/freeze']],
    'menu_bermasalah_pending' => ['label' => 'Berkas Bermasalah - Pending Job', 'description' => 'Daftar dan aksi pending job.', 'default' => true, 'menu' => true, 'paths' => ['berkas-bermasalah/pending']],
    'menu_bermasalah_disposisi' => ['label' => 'Berkas Bermasalah - Disposisi', 'description' => 'Menu disposisi berkas.', 'default' => true, 'menu' => true, 'paths' => ['berkas-bermasalah/dispo']],
    'menu_finance_in' => ['label' => 'Finance - IN', 'description' => 'Transaksi finance masuk.', 'default' => true, 'menu' => true, 'paths' => [['path' => 'finance/job-divisi', 'query' => ['type' => 'in']]]],
    'menu_finance_out' => ['label' => 'Finance - OUT', 'description' => 'Transaksi finance keluar.', 'default' => true, 'menu' => true, 'paths' => [['path' => 'finance/job-divisi', 'query' => ['type' => 'out']]]],
    'menu_finance_jurnal' => ['label' => 'Finance - Jurnal', 'description' => 'Laporan jurnal.', 'default' => true, 'menu' => true, 'paths' => ['finance/reports/jurnal']],
    'menu_finance_neraca' => ['label' => 'Finance - Neraca', 'description' => 'Laporan neraca.', 'default' => true, 'menu' => true, 'paths' => ['finance/reports/neraca']],
    'menu_finance_laba_kotor' => ['label' => 'Finance - Laba Kotor', 'description' => 'Laporan laba kotor.', 'default' => true, 'menu' => true, 'paths' => ['finance/reports/laba-kotor']],
    'menu_finance_laba_bersih' => ['label' => 'Finance - Laba Bersih', 'description' => 'Laporan laba bersih.', 'default' => true, 'menu' => true, 'paths' => ['finance/reports/laba-bersih']],
    'menu_hris_employee' => ['label' => 'HRIS - Employee', 'description' => 'Data karyawan.', 'default' => true, 'menu' => true, 'paths' => ['hris/employee']],
    'menu_hris_cuti' => ['label' => 'HRIS - Cuti Karyawan', 'description' => 'Pengelolaan cuti.', 'default' => true, 'menu' => true, 'paths' => ['hris/cuti']],
    'menu_hris_lembur' => ['label' => 'HRIS - Lembur Karyawan', 'description' => 'Pengelolaan lembur.', 'default' => true, 'menu' => true, 'paths' => ['hris/lembur']],
    'menu_arsip_akta' => ['label' => 'Arsip - Akta', 'description' => 'Arsip akta.', 'default' => true, 'menu' => true, 'paths' => [['path' => 'arsip/bundle', 'except_query' => ['tipe' => 'ppat']]]],
    'menu_arsip_ppat' => ['label' => 'Arsip - PPAT', 'description' => 'Arsip PPAT.', 'default' => true, 'menu' => true, 'paths' => ['arsip/bundle?tipe=ppat']],
    'menu_arsip_warkah' => ['label' => 'Arsip - Warkah', 'description' => 'Arsip warkah.', 'default' => true, 'menu' => true, 'paths' => ['arsip/warkah']],
    'menu_laporan_nomor_notaris' => ['label' => 'Laporan - Penomoran Notaris', 'description' => 'Laporan nomor notaris.', 'default' => true, 'menu' => true, 'paths' => ['laporan/nomor-notaris', 'laporan/nomor-notaris/notaris', 'laporan/nomor-notaris/export/notaris']],
    'menu_laporan_nomor_ppat' => ['label' => 'Laporan - Penomoran PPAT', 'description' => 'Laporan nomor PPAT.', 'default' => true, 'menu' => true, 'paths' => ['laporan/nomor-notaris/ppat', 'laporan/nomor-notaris/export/ppat']],
    'menu_laporan_nomor_waarmerking' => ['label' => 'Laporan - Penomoran Waarmerking', 'description' => 'Laporan nomor waarmerking.', 'default' => true, 'menu' => true, 'paths' => ['laporan/nomor-notaris/waarmerking', 'laporan/nomor-notaris/export/waarmerking']],
    'menu_laporan_nomor_covernot' => ['label' => 'Laporan - Penomoran Cover Not', 'description' => 'Laporan nomor cover not.', 'default' => true, 'menu' => true, 'paths' => ['laporan/nomor-notaris/covernot', 'laporan/nomor-notaris/export/covernot']],
    'menu_laporan_nomor_surat_keluar' => ['label' => 'Laporan - Penomoran Surat Keluar', 'description' => 'Laporan nomor surat keluar.', 'default' => true, 'menu' => true, 'paths' => ['laporan/nomor-notaris/surat-keluar', 'laporan/nomor-notaris/export/surat-keluar']],
    'menu_laporan_nomor_legalisasi' => ['label' => 'Laporan - Penomoran Legalisasi', 'description' => 'Laporan nomor legalisasi.', 'default' => true, 'menu' => true, 'paths' => ['laporan/nomor-notaris/legalisasi', 'laporan/nomor-notaris/export/legalisasi']],
    'menu_laporan_nomor_wasiat' => ['label' => 'Laporan - Penomoran Wasiat', 'description' => 'Laporan nomor wasiat.', 'default' => true, 'menu' => true, 'paths' => ['laporan/nomor-notaris/wasiat', 'laporan/nomor-notaris/export/wasiat']],
    'menu_laporan_pemakaian_nomor' => ['label' => 'Laporan - Pemakaian Nomor', 'description' => 'Laporan pemakaian nomor.', 'default' => true, 'menu' => true, 'paths' => ['laporan/pemakaian-nomor']],
    'menu_laporan_pekerjaan_staff' => ['label' => 'Laporan - History Pekerjaan Staff', 'description' => 'Riwayat pekerjaan staff.', 'default' => true, 'menu' => true, 'paths' => ['laporan/list-pekerjaan-staff', 'laporan/detail-pekerjaan-staff']],
    'menu_laporan_job_divisi' => ['label' => 'Laporan - History Job Divisi', 'description' => 'Riwayat job divisi.', 'default' => true, 'menu' => true, 'paths' => ['laporan/list-job-divisi-history']],
    'menu_akses_role' => ['label' => 'Akses - Role & Permission', 'description' => 'Pengaturan role dan permission.', 'default' => true, 'menu' => true, 'paths' => ['akses/role']],
    'menu_akses_user' => ['label' => 'Akses - User', 'description' => 'Pengelolaan user.', 'default' => true, 'menu' => true, 'paths' => ['akses/user']],
    'menu_setting_perusahaan' => ['label' => 'Setting - Perusahaan', 'description' => 'Pengaturan perusahaan.', 'default' => true, 'menu' => true, 'paths' => ['setting/perusahaan']],
    'menu_setting_penomoran' => ['label' => 'Setting - Penomoran', 'description' => 'Pengaturan penomoran.', 'default' => true, 'menu' => true, 'paths' => ['setting/penomoran']],
    'menu_setting_workflow_akta' => ['label' => 'Setting - Workflow Job Akta', 'description' => 'Pengaturan workflow job akta.', 'default' => true, 'menu' => true, 'paths' => ['setting/workflow-akta']],
    'menu_setting_approval' => ['label' => 'Setting - Konfigurasi Approval', 'description' => 'Pengaturan approval.', 'default' => true, 'menu' => true, 'paths' => ['setting/approval']],
    'menu_setting_features' => ['label' => 'Setting - Fitur Tenant', 'description' => 'Pengaturan flag fitur tenant.', 'default' => true, 'menu' => true, 'paths' => ['setting/features']],
    'menu_setting_whatsapp' => ['label' => 'Setting - Nomor WhatsApp', 'description' => 'Pengaturan nomor WhatsApp.', 'default' => true, 'menu' => true, 'paths' => ['setting/wa']],
];
